Create services
AndreCabalo/projeto_onboarding pull request #3
Opened 2024-08-15 21:31 UTC by AndreCabalo

# Projeto Onboarding

<h2>Requisitos do projeto</h2>

<h3>Tecnologias Utilizadas:</h3>

  - Java 21
  - Spring Boot
  - Spring Data JPA
  - Banco de dados MySQL em Docker
  - Docker
  - RESTful API

<h3>Entidades Principais:</h3>

  - Item
  - ID (UUID)
  - Nome
  - Preço
  - Quantidade em estoque
  - Carrinho
  - ID (UUID)
  - Lista de Itens (muitos para muitos)
  - Data de criação
  - Valor total (calculado)

<h3>Regras de Negócio:</h3>

  - Não pode adicionar ao carrinho itens com quantidade maior do que a disponível em estoque.
  - O valor total do carrinho deve ser recalculado cada vez que um item é adicionado ou removido.
  - Não pode haver itens duplicados no carrinho.
  - Deve ser possível criar, atualizar e deletar itens no estoque.

<h3>Operações da API:</h3>

- Item:

  - Criar item
  - Atualizar item
  - Deletar item
  - Listar todos os itens
  - Buscar item por ID

- Carrinho:

  - Criar carrinho
  - Adicionar item ao carrinho
  - Remover item do carrinho
  - Listar todos os carrinhos
  - Buscar carrinho por ID
  - Passos para Implementação

<h3> Configuração do Ambiente:</h3>

- Configurar o ambiente de desenvolvimento com Java 21, Spring Boot e Docker.
- Criar um contêiner Docker para o banco de dados MySQL.
- Criar repositório no Github para subir o projeto.

<h3>Inicializar o Projeto Spring Boot:</h3>

- Usar o Spring Initializr para criar um novo projeto Spring Boot com dependências de Spring Web, Spring Data JPA e MySQL Driver.

<h3>Configuração do Banco de Dados:</h3>

- Configurar as propriedades do banco de dados no application.properties ou application.yml do Spring Boot.
- Configurar o Docker Compose para iniciar o contêiner do MySQL Database.

`docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cart mysql:9.0.1`

<h3>Criar Entidades e Repositórios:</h3>

- Criar classes de entidade para Item e Carrinho .
- Criar interfaces de repositório para Item e Carrinho que estendem JpaRepository.

<h3>Criar Serviços:</h3>

- Implementar serviços para gerenciar a lógica de negócio de Item e Carrinho .
- Garantir a validação de regras de negócio, como quantidade em estoque e cálculo de valor total.
- Adicionar logs ao longo da execução para ter tracking das execuções.
- Configurar o Exception Handler para capturar e expor de maneira consistente os erros.

<h3>Criar Controladores REST:</h3>

- Criar controladores REST para expor endpoints para as operações de Item e Carrinho .
- Seguir as melhores práticas RESTful, como usar os verbos HTTP adequados (GET, POST, PUT, DELETE) e status HTTP corretos.

<h3>Testar a API:Usar o Postman ou outra ferramenta similar para testar todos os endpoints da API.</h3>

- [ ]Escrever testes unitários para garantir que as regras de negócio estão sendo aplicadas corretamente.

2024-08-20 20:45 UTC, AndreCabalo commented on src/main/java/br/com/pagbanks/projeto_onboarding/service/CartService.java
> +                item.setAmount(item.getAmount() - 1);
Vi que o amount de item estava baixando rapido demais.. dupliquei indevidamente está linha sem querer.

2024-08-21 21:43 UTC, CaioRib requested changes

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/controller/ItemController.java
> +    }
Costuma-se usar o ResponseEntity por padrão nos retornos das APIs.
Ele enriquece a resposta com algumas informações e com ele você consegue personalizar headers, o status http de response.

No último vc usou. Só toma cuidado pra não conflitar o status do `@ResponseStatus` com o da ResponseEntity.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/controller/ItemController.java
> +    @Transactional
Acredito ser incomum o uso do `@Transactional` a nível de controller (eu particularmente nunca vi).

É interessante que o controle transacional seja feito na menor unidade possível, então só a nível de service ou até mesmo um método chamado pelo service é mais aconselhável.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/controller/CartController.java
> +
Mesmo comentário do outro controller relacionado ao ResponseEntity.

No `delete` não há nem o ResponseEntity nem `@ResponseStatus`

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/dto/CartDto.java
> +                }
A sacada é bacana, mas acho mais interessante o creationDate estar atrelado ao momento da criação do banco do que a criação do objeto. Anotações como @CreatedDate e @LastModifiedDate podem deixar a cargo do Hibernate/JPA controlar as datas.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/dto/CartDto.java
> +        }
Esse tipo de método que faz conversão é comumente chamado de mapper.
É possível utilizar frameworks como mapstruct para fazer mapeamento, mas também usar o java puro.
Ao invés de um construtor, o mais comum é um método estático com a nomenclatura 'from" ou 'to'. Exemplo nesse caso:
![image](https://github.com/user-attachments/assets/465e270b-1623-4f7b-bb51-d19745af80c4)

É estático para não poder ser chamado independente de instanciação da classe.

A leitura fica fluida:
É um CartDto from Cart.

![image](https://github.com/user-attachments/assets/15bb3bc5-0b4b-4cdd-85fa-d4c19a91c0e6)

Em uma classe focada na conversão, poderia ficar assim:
![image](https://github.com/user-attachments/assets/f7cbd1bf-3e5d-41d0-a4f2-a508cf70f1d7)


Essa necessidade de mapeamento é tão comum que temos frameworks como o Mapstruct que facilitam essas conversões.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/entity/Cart.java
> +    }
Semelhante aos outros comentários, é interessante deixar o controle de data pro ORM e o mapeamento de entidade -> DTOs fora do contexto da entidade. 

Pode ser uma classe utilitária de mapeamento que tenha um método estático:
![image](https://github.com/user-attachments/assets/e129d80e-f9fd-4f8e-bce3-d90d6ed6dcd0)

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/entity/Cart.java
> +    private Set<Item> listItens;
Nesse caso o set não vira uma coluna de Cart, acho que o `@Column` aqui está incorreto.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/exceptions/GlobalExceptionHandler.java
> +    }
O mais correto é o retorno de cada handler ser uma ResponseEntity. Eles funcionam como as respostas em caso de erro, por isso é interessante usar a mesma estrutura dos controllers.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/repository/ItemRepository.java
> +    Item findByName(String name);
Como uma evolução do projetinho, podemos pensar em alguma query um pouco mais complexa que possa ser escrita em JPQL, só pra exercitar.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/service/CartService.java
> +                cart.setTotalValue((cart.getTotalValue()) + item.getPrice());
Em uma implementação real é muito difícil que esse valor seja persistido. É o tipo de campo que é calculado toda vez que é requisitado.

Imagina que eu tenho um carrinho com x items, mas eu resolvo atualizar o preço de um dos itens. Fixando o valor no banco, o valor total vai precisar ser atualizado em todos os carrinhos em caso de alteração de preço de item.

Do jeito que tá, o preço ser alterado gera um insconsistência no valor total pós alteração, dado que se eu manipulo o mesmo carrinho criado antes da alteração e remover todos os itens, nunca vou ter o valor '0' no preço.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/service/CartService.java
> +        List<Cart> listCarts = cartRepository.findAll().stream().toList();
O findAll já retorna uma lista, não entendi a conversão 🤔

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/service/CartService.java
> +        return cartRepository.findAll();
Aqui houve uma segunda chamada no banco. Não era só retornar o objeto recuperado?

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/service/CartService.java
> +            return cartRepository.save(cart);
Essa regra funciona, mas em um carrinho real teríamos possibilidade de ter o mesmo item mais de uma vez em um carrinho. Enxerga como poderia ficar esse relacionamento?

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/service/ItemService.java
Ficar ligado à consitência dos logs. Idealmente, dado que usamos um motor de buscas como o Splunk, é legal manter a formatação consistente. Em algumas situações está faltando espaço pós vírgula.

Isso se aplica ao código também. Aqui usamos uma ferramenta chamada checkstyle que acusa quando um código está fora do padrão. Espaço após a definição de métodos é um exemplo de falta de formatação. Toda IDE tem um botão para ajustar, pode tentar criar o hábito de sempre apertar o botão de formatar nos arquivos que estiver mexendo.

2024-08-21 21:43 UTC, CaioRib commented on src/main/resources/application.properties
Um detalhe, costumamos preferir `.yaml` ao invés de `.properties`. Consideramos mais legível.

2024-08-21 21:43 UTC, CaioRib commented on src/main/resources/application.properties
> +server.error.include-stacktrace=never
Alguma motivação para esconder os traces dos erros?
Idealmente é bom deixar habilitado para debugs e troubleshootings.

2024-08-21 21:43 UTC, CaioRib commented on src/main/java/br/com/pagbanks/projeto_onboarding/entity/Cart.java
> +//    }
Cuidado com os comentários de codigo perdido. Isso pro sonarqube é considerado code smell. Salvo algumas situações muito específicas, não é uma boa prática deixar "lixo" no código.

2024-08-23 17:08 UTC, AndreCabalo commented on src/main/java/br/com/pagbanks/projeto_onboarding/controller/ItemController.java
> +    }
Boa! vlw Caio! acabei de alterar o ResponseEntity como padrão de retorno dos end-points.
E removi o @ResponseStatus pois, creio que ficaria redundante o @ResponseStatus com o retorno Entity. Obrigado pela dica!

2024-08-23 17:21 UTC, AndreCabalo commented on src/main/java/br/com/pagbanks/projeto_onboarding/controller/CartController.java
> +
Ajustado.

![image](https://github.com/user-attachments/assets/fda55781-d637-4336-a6d4-97017c465c63)

2024-08-23 17:23 UTC, AndreCabalo commented on src/main/java/br/com/pagbanks/projeto_onboarding/controller/CartController.java
> +
Ajustado:


![image](https://github.com/user-attachments/assets/37a8c341-327f-44d7-b3f8-cfe88ae5599e)

2024-09-02 20:16 UTC, closed without merging